name: Deploy container app
description: 'Deploy a container app and associated resources to azure'

outputs:
  container-app-existed:
    description: Indicate whether the container app already existed.
    value: ${{ steps.container-app-required-variables.outputs.container-app-exists }}
  principal-id:
    description: test
    value: ${{ steps.container-app-principal-id.outputs.principal-id }}

runs:
  using: "composite"
  steps:
  - name: get-container-app-required-variables
    id: container-app-required-variables
    shell: bash
    run: |
      caeId="$(az containerapp env list -g ${{ env.environment-resource-group-name }} --query '[?name==`'${{ env.container-app-environment-name }}'`].id | [0]')"
      containerAppId="$(az containerapp list -g ${{ env.resource-group-name }} --query '[?name==`'${{ env.container-app-name }}'`].id | [0]')"
      containerAppExists="$([[ $containerAppId == '' ]] && echo 0 || echo 1)"
      echo "$caeId"
      echo "cae-id=$caeId" >> $GITHUB_OUTPUT
      echo "container-app-exists=$containerAppExists" >> $GITHUB_OUTPUT

  - name: ensure-container-app-exists
    if: ${{ steps.container-app-required-variables.outputs.container-app-exists == 0 }}
    uses: azure/bicep-deploy@v2
    with:
      type: deployment
      operation: create
      name: deploy-empty-${{ env.service-type }}-container-app
      scope: resourceGroup
      subscription-id: ${{ env.subscription-id }}
      resource-group-name: ${{ env.resource-group-name }}
      template-file: ./.github/bicep/create-empty-container-app.bicep
      parameters: |
        app_config_name: app-config-${{ env.environment-name }}-tag
        app_insights_name: ${{ env.app-insights-name }}
        container_app_name: ${{ env.container-app-name }}
        environment: ${{ env.environment-name }}
        environment_resource_group_name: ${{ env.environment-resource-group-name }}
        sql_server_name: ${{ env.sql-server-name }}
        container_app_environment_id: ${{ steps.container-app-required-variables.outputs.cae-id }}
        service_type: ${{ env.service-type }}
        ghcr_username: ${{ env.ghcr-username }}
        ghcr_token: ${{ env.ghcr-token }}

  - name: get-container-app-principal-id
    id: container-app-principal-id
    shell: bash
    run: |
      principalId="$(az containerapp show --name ${{ env.container-app-name }} -g ${{ env.resource-group-name }} --query 'identity.principalId')"
      echo "latest-revision-no=$latestRevisionNo" >> $GITHUB_OUTPUT
      echo "principal-id=$principalId" >> $GITHUB_OUTPUT
