name: Ensure container app dependencies
description: 'Deploy container app associated resources to azure'

runs:
  using: "composite"
  steps:
  - name: ensure-resource-group-and-check-resource-existence
    id: resource-existence
    shell: bash
    run: |
      resourceGroupResponse="$(az group list --query '[?name==`'${{ env.resource-group-name }}'`].name')"
      resourceGroupExists="$([[ $resourceGroupResponse == '[]' ]] && echo 0 || echo 1)"
      sqlDatabaseId="$(az sql db list -s ${{ env.sql-server-name }} -g ${{ env.environment-resource-group-name }} --query '[?name==`'${{ env.sql-database-name }}'`].id | [0]')"
      sqlDatabaseExists="$([[ $sqlDatabaseId == '' ]] && echo 0 || echo 1)"
      if [[ $resourceGroupExists == 0 ]]; then
        az group create -n ${{ env.resource-group-name }} -l uksouth --subscription ${{ env.subscription }}
        appInsightsExists=0
      else
        appInsightsId="$(az monitor app-insights component show -g ${{ env.resource-group-name }} --query '[?name==`'$${{ env.app-insights-name }}'`].id | [0]')"
        appInsightsExists="$([[ $appInsightsId == '' ]] && echo 0 || echo 1)"
      fi
      echo "app-insights-exists=$appInsightsExists" >> $GITHUB_OUTPUT
      echo "sql-database-exists=$sqlDatabaseExists" >> $GITHUB_OUTPUT


  - name: ensure-app-insights-exists
    if: ${{ steps.resource-existence.outputs.app-insights-exists == 0 }}
    uses: azure/arm-deploy@v2
    with:
      resourceGroupName: ${{ env.resource-group-name }}
      template: ${{ github.action_path }}/bicep/create-app-insights.bicep
      deploymentName: 'deploy-${{ env.app-insights-name }}'
      scope: resourcegroup
      parameters: log_analytics_workspace_name=${{ env.log-analytics-workspace-name }} log_analytics_resource_group_name=${{ env.environment-resource-group-name }} app_insights_name=${{ env.app-insights-name }}

  - name: ensure-sql-database-exists
    if: ${{ steps.resource-existence.outputs.sql-database-exists == 0 }}
    uses: azure/arm-deploy@v2
    with:
      resourceGroupName: ${{ env.environment-resource-group-name }}
      template: ${{ github.action_path }}/bicep/create-database.bicep
      deploymentName: 'create-${{ env.sql-database-name }}'
      scope: resourcegroup
      parameters: database_name=${{ env.sql-database-name }} server_name=${{ env.sql-server-name }}
