name: Build docker image
description: 'Build docker image and upload as artifact'

inputs:
  project-name-root:
    description: The name of the project for this build
    required: true
  dockerfile-name-root:
    description: The name of the dockerfile to use
    required: true
  image-name-root:
    description: The name of the docker image to generate
    required: true
  service-type:
    description: The type of service being deployed
    required: true
  version-number:
    description: The version to give to nuget packages
    required: true

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v6

  - name: Setup .Net
    uses: actions/setup-dotnet@v5
    with:
      dotnet-version: 10.0.x
      source-url: https://nuget.pkg.github.com/sming-code/index.json
    env:
      NUGET_AUTH_TOKEN: ${{ github.token }}

  - name: Get lower case service type
    id: lower-case-service-type
    shell: bash
    run: |
      serviceTypeLower=${SERVICE_TYPE,,}
      echo "$serviceTypeLower"
      projectNameFull="$PROJECT_NAME_ROOT.$SERVICE_TYPE"
      dockerfileNameFull="$DOCKERFILE_NAME_ROOT.$serviceTypeLower"
      imageNameFull="$IMAGE_NAME_ROOT-$serviceTypeLower"
      echo "project-name-full=$projectNameFull" >> $GITHUB_OUTPUT
      echo "dockerfile-name-full=$dockerfileNameFull" >> $GITHUB_OUTPUT
      echo "image-name-full=$imageNameFull" >> $GITHUB_OUTPUT
    env:
      PROJECT_NAME_ROOT: ${{ inputs.project-name-root }}
      DOCKERFILE_NAME_ROOT: ${{ inputs.dockerfile-name-root }}
      IMAGE_NAME_ROOT: ${{ inputs.image-name-root }}
      SERVICE_TYPE: ${{ inputs.service-type }}

  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v4

  - name: Repoint dockerfile to point to correct project (needed particularly for entrypoint)
    shell: bash
    run: sed -i -E 's/\$Project_Name/${{ steps.lower-case-service-type.outputs.project-name-full }}/g' "${{ steps.lower-case-service-type.outputs.dockerfile-name-full }}"

  - name: Build docker image
    uses: docker/build-push-action@v7
    with:
      context: .
      file: ${{ steps.lower-case-service-type.outputs.dockerfile-name-full }}
      build-args: |
        Nuget_CustomFeedUserName=USERNAME
        Nuget_CustomFeedPassword=${{ github.token }}
      tags: |
        ${{ steps.lower-case-service-type.outputs.image-name-full }}:${{ inputs.version-number }}
      outputs: type=docker,dest=${{ runner.temp }}/docker-image.tar

  - name: Load image
    shell: bash
    run: |
      docker load --input ${{ runner.temp }}/docker-image.tar
      docker image ls -a

  - name: Publish to GPR
    shell: bash
    run: |
      docker tag ${{ inputs.image-name-full }}:${{ inputs.version-number }} ghcr.io/sming-code/${{ inputs.image-name-full }}:latest
      docker tag ${{ inputs.image-name-full }}:${{ inputs.version-number }} ghcr.io/sming-code/${{ inputs.image-name-full }}:${{ inputs.version-number }}
      docker push ghcr.io/sming-code/${{ inputs.image-name-full }}:latest
      docker push ghcr.io/sming-code/${{ inputs.image-name-full }}:${{ inputs.version-number }}

  # - name: Upload artifact
  #   uses: actions/upload-artifact@v7
  #   with:
  #     name: ${{ inputs.service-type }}
  #     path: ${{ runner.temp }}/docker-image.tar
  #     retention-days: 5


  #   steps:
  #   - name: Login to Github Container Registry
  #     uses: docker/login-action@v4
  #     with:
  #       registry: ghcr.io/sming-code
  #       username: ${{ github.repository_owner }}
  #       password: ${{ secrets.GITHUB_TOKEN }}
  #   - name: Setup Docker Buildx
  #     uses: docker/setup-buildx-action@v4
  #   - name: Download Build Artifacts
  #     uses: actions/download-artifact@v8
  #     with:
  #       name: ${{ inputs.archive-name }}
  #       path: ${{ runner.temp }}
  #   - name: Load image
  #     run: |
  #       docker load --input ${{ runner.temp }}/docker-image.tar
  #       docker image ls -a
  #   - name: Publish to GPR
  #     run: |
  #       docker tag ${{ inputs.image-name-root }}:${{ inputs.version-number }} ghcr.io/sming-code/${{ inputs.image-name-root }}:latest
  #       docker tag ${{ inputs.image-name-root }}:${{ inputs.version-number }} ghcr.io/sming-code/${{ inputs.image-name-root }}:${{ inputs.version-number }}
  #       docker push ghcr.io/sming-code/${{ inputs.image-name-root }}:latest
  #       docker push ghcr.io/sming-code/${{ inputs.image-name-root }}:${{ inputs.version-number }}