name: Get Version number
description: 'Get version details for this repository'

inputs:
  major:
    description: The major part of the required version
    required: true
    default: '1'
  minor:
    description: The minor part of the required version
    required: true
    default: '0'
outputs:
  last-release-tag:
    description: The tag for the previous release
    value: ${{ steps.get-version.outputs.last-release-tag }}
  version-no:
    description: The version number to use for this build
    value: ${{ steps.get-version.outputs.version-no }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v6
    - id: get-version
      shell: bash
      run: |
        latestReleaseTag="$(gh release list -L 1 --json tagName -q .[0].tagName)"
        latestReleaseTagVersionRoot=$(echo $latestReleaseTag | awk -F'.' '{ OFS="."; print $1, $2 "." }')
        latestReleaseTagBuild=$(echo $latestReleaseTag | awk -F'.' '{ print $3 }')
        newReleaseVersionRoot="v$Major_Version.$Minor_Version."
        newReleaseVersionTag=$([ "$latestReleaseTagVersionRoot" = "$newReleaseVersionRoot" ] && echo "$newReleaseVersionRoot$((latestReleaseTagBuild+1))" || echo "$newReleaseVersionRoot""0" )
        echo "last-release-tag=$latestReleaseTag" >> $GITHUB_OUTPUT
        echo "version-no=${newReleaseVersionTag:1}" >> $GITHUB_OUTPUT
      env:
        Major_Version: ${{ inputs.major }}
        Minor_Version: ${{ inputs.minor }}
