name: Deploy container app to environment

on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
      app-insights-name:
        required: true
        type: string
      branch-suffix:
        required: true
        type: string
      container-app-environment-name:
        required: true
        type: string
      environment-name:
        required: true
        type: string
      environment-resource-group-name:
        required: true
        type: string
      log-analytics-workspace-name:
        required: true
        type: string
      resource-group-name:
        required: true
        type: string
      sql-database-name:
        required: true
        type: string
      sql-server-name:
        required: true
        type: string
      subscription:
        required: true
        type: string
      version-no:
        required: true
        type: string
      reservation-svc-target-branch:
        required: true
        type: string
      ppl-svc-target-branch:
        required: true
        type: string
      broken-svc-target-branch:
        required: true
        type: string
    secrets:
      ghcr-username:
        required: true
      ghcr-token:
        required: true
      client-id:
        required: true
      tenant-id:
        required: true
      subscription-id:
        required: true

permissions:
  id-token: write
  contents: read

env:
  app-name: ${{ inputs.app-name }}
  app-insights-name: ${{ inputs.app-insights-name }}
  branch-suffix: ${{ inputs.branch-suffix }}
  container-app-environment-name: ${{ inputs.container-app-environment-name }}
  environment-name: ${{ inputs.environment-name }}
  environment-resource-group-name: ${{ inputs.environment-resource-group-name }}
  log-analytics-workspace-name: ${{ inputs.log-analytics-workspace-name }}
  resource-group-name: ${{ inputs.resource-group-name }}
  sql-database-name: ${{ inputs.sql-database-name }}
  sql-server-name: ${{ inputs.sql-server-name }}
  subscription: ${{ inputs.subscription }}
  version-no: ${{ inputs.version-no }}
  reservation-svc-target-branch: ${{ inputs.reservation-svc-target-branch }}
  ppl-svc-target-branch: ${{ inputs.ppl-svc-target-branch }}
  broken-svc-target-branch: ${{ inputs.broken-svc-target-branch }}
  ghcr-token: ${{ secrets.ghcr-token }}
  ghcr-username: ${{ secrets.ghcr-username }}
  subscription-id: ${{ secrets.subscription-id }}

jobs:
  deploy-to-environment-dependencies:
    name: Deploy to environment (ensure dependencies)
    environment: ${{ inputs.environment-name }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: azure/login@v3
      with:
        client-id: ${{ secrets.client-id }}
        tenant-id: ${{ secrets.tenant-id }}
        subscription-id: ${{ secrets.subscription-id }}

    - uses: sming-code/ensure-container-app-dependencies-action@v1

    - id: ensure-api-container-app
      uses: ./.github/actions/ensure-container-app
      env:
        service-type: api
        container-app-name: 'customer-api-${{ env.environment-name }}${{ inputs.branch-suffix }}'
      background: true

    - id: ensure-worker-container-app
      uses: ./.github/actions/ensure-container-app
      env:
        service-type: worker
        container-app-name: 'customer-worker-${{ env.environment-name }}${{ inputs.branch-suffix }}'
      background: true

    - name: Wait for container apps to be ensured
      wait: [
        ensure-api-container-app,
        ensure-worker-container-app,
      ]

    - name: get-container-app-principal-ids
      id: container-app-principal-ids
      shell: bash
      run: |
        principalIdApi="$(az containerapp show --name customer-api-${{ env.environment-name }}${{ inputs.branch-suffix }} -g ${{ env.resource-group-name }} --query 'identity.principalId')"
        principalIdWorker="$(az containerapp show --name customer-worker-${{ env.environment-name }}${{ inputs.branch-suffix }} -g ${{ env.resource-group-name }} --query 'identity.principalId')"
        echo "principal-id-api=$principalIdApi" >> $GITHUB_OUTPUT
        echo "principal-id-worker=$principalIdWorker" >> $GITHUB_OUTPUT

    - name: ensure-container-app-api-sql-server-access
      if: ${{ steps.ensure-api-container-app.outputs.container-app-exists == 0 }}
      uses: azure/sql-action@v2.3
      with:
        connection-string: Server=tcp:${{ env.sql-server-name }}.database.windows.net,1433;Initial Catalog=${{ env.sql-database-name }};Authentication=Active Directory Default;Encrypt=True;
        path: ./.github/sql/initialize-user.sql
        arguments: '-v CaName=customer-api-${{ env.environment-name }}${{ inputs.branch-suffix }}'

    - name: ensure-container-app-worker-sql-server-access
      if: ${{ steps.ensure-worker-container-app.outputs.container-app-exists == 0 }}
      uses: azure/sql-action@v2.3
      with:
        connection-string: Server=tcp:${{ env.sql-server-name }}.database.windows.net,1433;Initial Catalog=${{ env.sql-database-name }};Authentication=Active Directory Default;Encrypt=True;
        path: ./.github/sql/initialize-user.sql
        arguments: '-v CaName=customer-worker-${{ env.environment-name }}${{ inputs.branch-suffix }}'

    - id: create-api-container-app-revision
      uses: ./.github/actions/deploy-container-app
      env:
        service-type: api
        container-app-image: 'customer-api'
        container-app-name: 'customer-api-${{ env.environment-name }}${{ inputs.branch-suffix }}'
      background: true

    - id: create-worker-container-app-revision
      uses: ./.github/actions/deploy-container-app
      env:
        service-type: worker
        container-app-image: 'customer-worker'
        container-app-name: 'customer-worker-${{ env.environment-name }}${{ inputs.branch-suffix }}'
      background: true

    - name: Wait for container apps to be deployed
      wait: [
        create-api-container-app-revision,
        create-worker-container-app-revision,
      ]
