name: Customer service pipeline.

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      deploy-to-dev:
        description: 'Deploy branch container to dev environment for testing'
        required: false
        type: boolean
        default: false
      log-level:
        description: Log level to use
        type: choice
        default: Warning
        options:
          - Trace
          - Debug
          - Information
          - Warning
          - Error
          - Critical
      reservation-svc-target-branch:
        description: Branch to target for Reservation Service api client
        type: choice
        options:
          - default
          - branch
        default: default
        required: true

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  log-level: ${{ inputs.log-level }}
  reservation-svc-target-branch: ${{ inputs.reservation-svc-target-branch }}

jobs:
  variables:
    name: Generate variables
    runs-on: ubuntu-latest
    steps:
    - uses: sming-code/get-version-no-action@v1
      id: get-version
      with:
        major: 1
        minor: 0
    outputs:
      version-no: ${{ steps.get-version.outputs.version-no }}
      last-release-tag: ${{ steps.get-version.outputs.last-release-tag }}

  build-test:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
    - uses: sming-code/build-test-action@v1

  build-docker-images:
    name: Build docker images
    runs-on: ubuntu-latest
    needs: [ variables, build-test ]
    strategy:
      fail-fast: true
      matrix:
        service-type: ${{ fromJson('["Api","Worker"]') }}
    steps:
    - uses: sming-code/build-docker-image-action@v1
      with:
        project-name-root: DemoApp.Services.Customers
        image-name-root: customer
        dockerfile-name-root: Dockerfile
        service-type: ${{ matrix.service-type }}
        version-number: ${{ needs.variables.outputs.version-no }}

  get-branch-suffix:
    name: Get branch suffix
    if: ${{ (github.ref == 'refs/heads/main') || (inputs.deploy-to-dev == true) }}
    runs-on: ubuntu-latest
    steps:
    - uses: sming-code/get-branch-suffix-action@v1
      id: get-suffix
      with:
        branch-name: ${{ case(github.head_ref == '', github.ref_name, github.head_ref) }}
    outputs:
      branch-suffix: ${{ steps.get-suffix.outputs.branch-suffix }}

  deploy-dev:
    name: Deploy container app and related resources to dev environment
    needs: [ variables, get-branch-suffix, build-docker-images ]
    if: ${{ (github.ref == 'refs/heads/main') || (inputs.deploy-to-dev == true) }}
    uses: ./.github/workflows/deploy-container-app-to-environment.yml
    with:
      app-name: customer
      app-insights-name: insight-customer-dev${{ needs.get-branch-suffix.outputs.branch-suffix }}
      branch-suffix: ${{ needs.get-branch-suffix.outputs.branch-suffix }}
      container-app-environment-name: caenv-dev-tag-private
      environment-name: dev
      environment-resource-group-name: rg-dev-tag
      log-analytics-workspace-name: log-analytics-dev-tag
      resource-group-name: ${{ case(needs.get-branch-suffix.outputs.branch-suffix == '', 'rg-customer-dev', format('rg-dev{0}', needs.get-branch-suffix.outputs.branch-suffix)) }}
      sql-database-name:  sql-customer-dev${{ needs.get-branch-suffix.outputs.branch-suffix }}
      sql-server-name:  dev-tag
      subscription: sub-tag-testing
      version-no: ${{ needs.variables.outputs.version-no }}
    secrets:
      ghcr-username: ${{ secrets.GHCR_USERNAME }}
      ghcr-token: ${{ secrets.GHCR_TOKEN }}
      client-id: ${{ secrets.AZURE_CLIENT_ID_DEV }}
      tenant-id: ${{ secrets.AZURE_TENANT_ID_DEV }}
      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}
