name: Customer service pipeline.

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  variables:
    name: Generate variables
    runs-on: ubuntu-latest
    steps:
    - uses: sming-code/get-version-no-action@v1
      id: get-version
      with:
        major: 1
        minor: 0
    - name: Display done
      run: echo "Variables loaded..."
    outputs:
      project-name-root: DemoApp.Services.Customers
      image-name-root: demo-customer-svc
      version-no: ${{ steps.get-version.outputs.version-no }}
      last-release-tag: ${{ steps.get-version.outputs.last-release-tag }}

  build-test:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
    - uses: sming-code/build-test-action@v1

  build-docker-images:
    name: Build docker images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        service-type:
          - Api
          # - Worker
    needs: [ variables, build-test ]
    steps:
    - uses: sming-code/build-docker-image-action@v1
      with:
        project-name-root: ${{ needs.variables.outputs.project-name-root }}
        image-name-root: ${{ needs.variables.outputs.image-name-root }}
        dockerfile-name-root: Dockerfile
        service-type: ${{ matrix.service-type }}
        version-number: ${{ needs.variables.outputs.version-no }}

  create-release:
    name: Create release
    needs: [ variables, build-docker-images ]
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/add-github-release.yaml
    with:
      version-number: ${{ needs.variables.outputs.version-no }}
      previous-tag: ${{ needs.variables.outputs.last-release-tag }}