name: Push to container app

on:
  workflow_call:
    inputs:
      image-name:
        type: string
        required: true
      version-number:
        type: string
        required: true

jobs:
  deployment:
    name: Push image to container app
    runs-on: ubuntu-latest

    steps:
    - uses: azure/login@v3
      with:
        client-id: ${{ secrets.CLIENT_ID }}
        tenant-id: ${{ secrets.TENANT_ID }}
        subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
      secrets:
        clientId: ${{ secrets.AZURE_CLIENT_ID }}
        tenantId: ${{ secrets.AZURE_TENANT_ID }}
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - uses: azure/container-apps-deploy-action@v1
      with:
        containerAppName: test-container-app-name
        resourceGroup: test-container-app-resource-group
        imageToDeploy: ghcr.io/sming-code/${{ inputs.image-name }}:${{ inputs.version-number }}
        registryUrl: ghcr.io
        registryUsername: ${{ secrets.GHCR_USERNAME }}
        registryPassword: ${{ secrets.GHCR_TOKEN }}
